version: "3.8"

services:
  app:    
    restart: always
    build:
      context: ./frontend
    container_name: node-app
    volumes:
      - ./frontend:/usr/src
      - /usr/src/node_modules
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
      - HOST=0.0.0.0
    stdin_open: true
    tty: true
